import tensorflow.keras instead of just keras
otherwise I got:

```
Traceback (most recent call last):
  File "/tmp/venv3/bin/dfpl", line 5, in <module>
    from dfpl.__main__ import main
  File "/tmp/venv3/lib/python3.8/site-packages/dfpl/__main__.py", line 11, in <module>
    from dfpl import feedforwardNN as fNN
  File "/tmp/venv3/lib/python3.8/site-packages/dfpl/feedforwardNN.py", line 18, in <module>
    from keras.optimizers import SGD
ImportError: cannot import name 'SGD' from 'keras.optimizers' (/tmp/venv3/lib/python3.8/site-packages/keras/optimizers.py)
```